### PR TITLE
add streams support, unroll loops

### PR DESCRIPTION
**Pull request by fanatid**
Based on #11 
Ref: #7 #8 

based on [hash-base](https://github.com/crypto-browserify/hash-base)
package was full rewritten, so I change license to MIT

### CODE REVIEW

**Comment by dcousens** [comment]
> package was full rewritten, so I change license to MIT

Ping @jprichardson,  this should be fine,  but,  just in case.

**Comment by dcousens** [comment]
@fanatid rebase please,  simpler diffs.

**Comment by fanatid** [comment]
@dcousens rebased

**Comment by jprichardson** [comment]
Will review on Monday.

**Comment by jprichardson** [comment]
Nice work on `hash-base`! ACK. Looks good. License change looks good.

**Pull request merged**
