### PR TITLE
little optimizations

### PR DESCRIPTION
**Pull request by fanatid**
Not so much:

old:
```
$ SEED=123 node bench-hash.js create-hash ripemd160
...
76, 4466835, 13915.373831775702, 321
77, 5463865, 13728.304020100502, 398
78, 6683439, 13866.056016597511, 482
79, 8175230, 13903.452380952382, 588
80, 10000000, 14285.714285714286, 700
```

new:
```
$ SEED=123 node bench-hash.js create-hash ripemd160
...
76, 4466835, 13060.921052631578, 342
77, 5463865, 14045.925449871465, 389
78, 6683439, 14250.402985074626, 469
79, 8175230, 14317.39054290718, 571
80, 10000000, 14684.287812041115, 681
```

cc @dcousens 
related PR: #7

### CODE REVIEW

**Comment by dcousens** [comment]
TBH that looks to be within statistic variations?

**Comment by fanatid** [comment]
yes, I also think so
but I should note that I remove bytes swap for words

**Comment by dcousens** [comment]
That alone is probably worth it.  ACK

**Comment by dcousens** [comment]
Though is that less readable/reviewable?

**Comment by fanatid** [comment]
Probably is little more readable because I remove some extra lines.

**Comment by dcousens** [comment]
Why the close?  I somehow missed this.

**Comment by dcousens** [comment]
Thanks @fanatid,  ping me next time :).
Agreed, this is much clearer.

**Comment by dcousens** [comment]
> but I should note that I removed byte swapping for words

For what it is worth, I misunderstood this entirely, thinking you'd changed the algorithm to not use byte-swapping at all.
Instead, you just now use the standard functions (!!!),  perfect.

Thanks again.

**Pull request merged**
