### PR TITLE
Added LICENSE file to repo

### PR DESCRIPTION
**Pull request by janhagen**

### CODE REVIEW

**Comment by dcousens** [comment]
Same points of discussion as were made in https://github.com/crypto-browserify/browserify-rsa/pull/4.

> Copyright (c) 2014-2015 JP Richardson & contributors

Would probably be best.
Also, the date needs to be current (2015), also please use the the MIT license text formatted as in https://github.com/crypto-browserify/browserify-rsa/pull/4/files.

**Comment by janhagen** [comment]
All valid points.
I'll happily change to the MIT license instead but the current README file 'sort of' indicates a BSD license. My updated pull request therefore changes the README.md as well.

**Comment by dcousens** [comment]
@jprichardson can you chime in,  did you prefer the BSD license for any reason?

**Comment by jprichardson** [comment]
> @jprichardson can you chime in, did you prefer the BSD license for any reason?

Yes, because most of the code was extracted from CryptoJS which is licensed BSD v3. So rather than consider the legal issues of relicensing, I just stuck with the same license.

I don't know to what degree a person can relicense code? If it's changed 10%? 80%? Never?

**Comment by dcousens** [comment]
You'd have to basically delete the code, and re-implement the algorithm from scratch.  That is, without reference.  IANAL

**Comment by jprichardson** [comment]
> At that point, it should be fine?

I'd think it'd be fine legally, it's also fine by me. 

But I must ask, why not just stick with the BSDv3? We know the lib is working and reimplementing an algorithm just to convert to MIT (from BSDv3) doesn't feel like the best use of time. Is the BSDv3 restricting us in some way?

**Comment by janhagen** [comment]
I'm pretty sure the BSD3-Clause lets license your work under whatever License you want. It is not like the copyleft licenses associated with the GPL. 
So long as you acknowledge the fact that you've used BSD3-Clause licensed code to build your stuff (by including the original author's names and the standard text required by the license somewhere in your code) you can license your code under whatever terms you want. 

Compare with the Apple license acknowledgement files. Those things are massive....

An example can be found here: http://www.apple.com/legal/internet-services/maps/oss-acknowledgements/ but there are others. For instance one distributed with Final Cut Pro. 

Yet another pull request adds an ACKNOWLEDGEMENT file to the repo.

**Comment by fanatid** [comment]
license was changed :)
please create new PR if you still want add this file

**Pull request closed without merging**
